### ISSUE TITLE
Implement client unit test FW

### ISSUE THREAD

**Issue by markmcsherry** [markmcsherry/theseus#8]
# Details
Implement client unit test FW

# Tasks
- [ ] Bring in Test FW for client side 
- [ ] Setup test folders
- [ ] Implement simple test(s) to validate
